
POST http://localhost:3000/api/v1/tours/611fed218be8f41ea19f1602/reviews  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTAyMzNmNjJmOTk0YjEwMTZmZTY2NCIsImlhdCI6MTYyOTY0NDg4MSwiZXhwIjoxNjM3NDIwODgxfQ.W8zoOoiJmsQTEnxABPByRpmOWuB05Z0dvHAy4mVv6Bg
Content-Type: application/json

{
    "review":"Amazing",
    "rating":4
}