POST http://localhost:3000/api/v1/users/signup
Content-Type: application/json

{
    "name":"Yasin",
    "email":"veliyev.yasin@gmail.com",
    "password":"123456789",
    "passwordConfirm":"123456789",
    "role":"admin"
}