post http://localhost:3000/api/v1/users/updateme
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGExZTFhMmY4ZmI4MTRiNTZmYTE4MiIsImlhdCI6MTYzMDM0NDM0MiwiZXhwIjoxNjM4MTIwMzQyfQ.sXablZ5pcAoev3iCNSfr20dGvNUwDQBYRBjYcmFuPqg

{    
    "name":"YasinVeliyev"
}