patch http://localhost:3000/api/v1/users/updatepassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTAyNDA2MmIyZTBhYjNlMzAxYTI4NiIsImlhdCI6MTYyOTEzMjgwMiwiZXhwIjoxNjM2OTA4ODAyfQ.ZXd-XQRQ1FZKssWNefBUrRkAfUs7qOHnQADpNk94F9o

{   "passwordCurrent":"pass1234",
    "password":"pass1234",
    "passwordConfirm":"pass1234"
}