POST http://localhost:3000/api/v1/tours HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjUyNTQxNWZmMGVjMWEyMWUzYzg4NiIsImlhdCI6MTYzMDQzMzg3NywiZXhwIjoxNjM4MjA5ODc3fQ.6B_5kw8UN7EcaKWmGWyZrhpTQWnigjHBSP15R7XaLK8
content-type: application/json

{
  "name": "The Sports Lovers 515",
  "duration": 14,
  "maxGroupSize": 8,
  "difficulty": "difficult",
  "ratingsAverage": 4.7,
  "ratingsQuantity": 28,
  "startLocation": {
      "description": "Yellowknife, CAN",
      "type": "Point",
      "coordinates": [-114.406097, 62.439943],
      "address": "Yellowknife, NT X1A 2L2, Canada"
    },
  "price": 2997,
  "summary": "Surfing, skating, parajumping, rock climbing and more, all in one tour",
  "description": "Nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\nVoluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur!",
  "imageCover": "1.jpeg",
  "images": [],
   "startDates": ["2021-07-19,10:00", "2021-09-06,10:00", "2022-03-18,10:00"],
   "guides":["611020fa5dc126ab538eed99","6110233f62f994b1016fe664"]
}